version: '3.4'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: sh -c "bundle install && yarn install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        ports:
            - "3000:3000"
        environment:
            BUNDLE_PATH: /bundle/vendor #New
        volumes:
            - .:/app
            - gem_cache:/bundle/vendor
            - node_modules:/app/node_modules

    database:
        image: postgres:alpine
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - db_data:/var/lib/postgresql/data
volumes:
    gem_cache:
    db_data:
    node_modules: